# ansible/inventory/production.ini
[k8s_masters]
master01 ansible_host=10.0.1.10 ansible_user=ubuntu

[k8s_workers]
worker01 ansible_host=10.0.1.11 ansible_user=ubuntu
worker02 ansible_host=10.0.1.12 ansible_user=ubuntu

[k8s_cluster:children]
k8s_masters
k8s_workers

[all:vars]
ansible_ssh_private_key_file=~/.ssh/shopflow.pem
ansible_python_interpreter=/usr/bin/python3
